#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the ethernetGateway_user.mk file instead.
#

# Constants automatically defined by the selected modules
ethernetGateway_DEBUG = 1

# Our target application
TRG += ethernetGateway

ethernetGateway_PREFIX = "arm-none-eabi-"

ethernetGateway_SUFFIX = ""

ethernetGateway_SRC_PATH = projects/ethernetGateway

ethernetGateway_HW_PATH = projects/ethernetGateway/hw

# Files automatically generated by the wizard. DO NOT EDIT, USE ethernetGateway_USER_CSRC INSTEAD!
ethernetGateway_WIZARD_CSRC = \
     \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ethernetGateway_USER_PCSRC INSTEAD!
ethernetGateway_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ethernetGateway_USER_CPPASRC INSTEAD!
ethernetGateway_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ethernetGateway_USER_CXXSRC INSTEAD!
ethernetGateway_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE ethernetGateway_USER_ASRC INSTEAD!
ethernetGateway_WIZARD_ASRC = \
	 \
	#

ethernetGateway_CPPFLAGS = -D'CPU_FREQ=(84000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(ethernetGateway_HW_PATH) -I$(ethernetGateway_SRC_PATH) $(ethernetGateway_CPU_CPPFLAGS) $(ethernetGateway_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_LDFLAGS = $(ethernetGateway_CPU_LDFLAGS) $(ethernetGateway_WIZARD_LDFLAGS) $(ethernetGateway_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_CPPAFLAGS = $(ethernetGateway_CPU_CPPAFLAGS) $(ethernetGateway_WIZARD_CPPAFLAGS) $(ethernetGateway_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_CSRC = $(ethernetGateway_CPU_CSRC) $(ethernetGateway_WIZARD_CSRC) $(ethernetGateway_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_PCSRC = $(ethernetGateway_CPU_PCSRC) $(ethernetGateway_WIZARD_PCSRC) $(ethernetGateway_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_CPPASRC = $(ethernetGateway_CPU_CPPASRC) $(ethernetGateway_WIZARD_CPPASRC) $(ethernetGateway_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_CXXSRC = $(ethernetGateway_CPU_CXXSRC) $(ethernetGateway_WIZARD_CXXSRC) $(ethernetGateway_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_ASRC = $(ethernetGateway_CPU_ASRC) $(ethernetGateway_WIZARD_ASRC) $(ethernetGateway_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
ethernetGateway_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S
ethernetGateway_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
ethernetGateway_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_SAM3X8__
ethernetGateway_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/clock_sam3.c
ethernetGateway_PROGRAMMER_CPU = sam3
ethernetGateway_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/sam3x8_rom.ld
ethernetGateway_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
ethernetGateway_CPU = cortex-m3
ethernetGateway_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
ethernetGateway_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
ethernetGateway_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-sam3x.sh

include $(ethernetGateway_SRC_PATH)/ethernetGateway_user.mk
